# Generated by Django 2.0 on 2019-10-24 09:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='libs.TimeStampedModel')),
                ('mobile', models.BigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(5000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('is_verified', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=5)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(db_index=True, max_length=128, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('address', models.TextField(default='')),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'api_user',
            },
            bases=('libs.timestampedmodel',),
        ),
    ]
